### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by MohammadSalehi72** [cutright/DVHA-DICOM-Editor#8]
Hi Dan
I tried to install DVHA-DICOM-Editor with pip but got an error :
"Traceback (most recent call last):
  File "C:\Python\lib\site-packages\dvhaedit\main.py", line 954, in OnInit
    self.frame = MainFrame(None, wx.ID_ANY, "DVHA DICOM Editor v%s" % __version__)
  File "C:\Python\lib\site-packages\dvhaedit\main.py", line 100, in __init__
    self.__do_layout()
  File "C:\Python\lib\site-packages\dvhaedit\main.py", line 235, in __do_layout
    row_sizer.Add(self.force_open, 0, wx.ALIGN_RIGHT | wx.RIGHT, 15)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2098) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers OnInit returned false, exiting... "
I also cloned and again get this error.

OS: Win10
Python :3.7

**Comment by cutright** [comment]
This is interesting. Although I don't need `wx.ALIGN_RIGHT` on line 235, that doesn't crash on my work PC with Windows7.

Which version of wxPython are you using? I'm on `4.0.7.post2`:
`pip show wxpython`

I created a `v0.7.1.dev` branch with this change.  You could clone the new branch from here: 
https://github.com/cutright/DVHA-DICOM-Editor/tree/v0.7.1dev

But it might be much easier to just edit main.py for a temporary fix. If it resolves your error, I'll push a new release to the master branch and pip.

Change dvhaedit/main.py Line 235 from:
`row_sizer.Add(self.force_open, 0, wx.ALIGN_RIGHT | wx.RIGHT, 15)`
to
`row_sizer.Add(self.force_open, 0, wx.RIGHT, 15)`

**Comment by MohammadSalehi72** [comment]
This is a summary of wxpython installed on my windows:
Name: wxPython
Version: 4.1.0
Summary: Cross platform GUI toolkit for Python, "Phoenix" version
Home-page: http://wxPython.org/
Author: Robin Dunn
Author-email: robin@alldunn.com
License: wxWindows Library License (https://opensource.org/licenses/wxwindows.php)
Location: c:\python\lib\site-packages
Requires: numpy, pillow, six
Required-by: dvha-edit
Also, I changed the line 235 as you said, but still there is an previous error.

**Comment by cutright** [comment]
I get the same error on macOS when I upgrade wxPython to `4.1.0`.

```
(venv2) Ninjas-MacBook-Pro:DVHA-DICOM-Editor ninja$ python dvhaedit_app.py
Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/DVHA-DICOM-Editor/dvhaedit/main.py", line 954, in OnInit
    self.frame = MainFrame(None, wx.ID_ANY, "DVHA DICOM Editor v%s" % __version__)
  File "/Users/ninja/PycharmProjects/DVHA-DICOM-Editor/dvhaedit/main.py", line 100, in __init__
    self.__do_layout()
  File "/Users/ninja/PycharmProjects/DVHA-DICOM-Editor/dvhaedit/main.py", line 236, in __do_layout
    row_sizer.Add(self.search_sub_folders, 0, wx.ALIGN_RIGHT, 0)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/sizer.cpp(2098) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
OnInit returned false, exiting...
```

I'll see if I can figure out the issue, but I'll put a cap on the wxpython version in the meantime.

**Comment by MohammadSalehi72** [comment]
Thank you very much.
 I downgrade Wxpython version from 4.1.0 to 4.0.7.post2 via " pip install wxPython== 4.0.7.post2" and works for me.

Best Regards

**Comment by cutright** [comment]
I just pushed `v0.7.post1` to PyPI with:
https://github.com/cutright/DVHA-DICOM-Editor/blob/122e7e08958fc8e6dc34b4afe972a31830f02ecc/requirements.txt#L1

I found this issue posted on [wxPython's issue page](https://github.com/wxWidgets/Phoenix/issues/1612).

**Comment by MohammadSalehi72** [comment]
That's great
Thanks for your consistency

**Comment by cutright** [comment]
No problem, thank you for sharing.
